// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as outputs from "../types/output";

export interface DataSourceJsonData {
    /**
     * The role
     * ARN to be assumed by Grafana when using the CloudWatch data source.
     */
    assumeRoleArn?: string;
    /**
     * The authentication type
     * type used to access the data source.
     */
    authType: string;
    /**
     * 
     * A comma-separated list of custom namespaces to be queried by the CloudWatch
     * data source.
     */
    customMetricsNamespaces?: string;
    defaultRegion: string;
}

export interface DataSourceSecureJsonData {
    /**
     * The access key required
     * to access the data source.
     */
    accessKey: string;
    /**
     * The secret key required
     * to access the data source.
     */
    secretKey: string;
}
