// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-grafana/blob/master/website/docs/r/dashboard.html.markdown.
 */
export class Dashboard extends pulumi.CustomResource {
    /**
     * Get an existing Dashboard resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DashboardState, opts?: pulumi.CustomResourceOptions): Dashboard {
        return new Dashboard(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'grafana:index/dashboard:Dashboard';

    /**
     * Returns true if the given object is an instance of Dashboard.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Dashboard {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Dashboard.__pulumiType;
    }

    /**
     * The JSON configuration for the dashboard.
     */
    public readonly configJson!: pulumi.Output<string>;
    public readonly folder!: pulumi.Output<number | undefined>;
    /**
     * A URL "slug" for this dashboard, generated by Grafana by removing
     * certain characters from the dashboard name given as part of the `configJson`
     * argument. This can be used to generate the URL for a dashboard.
     */
    public /*out*/ readonly slug!: pulumi.Output<string>;

    /**
     * Create a Dashboard resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DashboardArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DashboardArgs | DashboardState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as DashboardState | undefined;
            inputs["configJson"] = state ? state.configJson : undefined;
            inputs["folder"] = state ? state.folder : undefined;
            inputs["slug"] = state ? state.slug : undefined;
        } else {
            const args = argsOrState as DashboardArgs | undefined;
            if (!args || args.configJson === undefined) {
                throw new Error("Missing required property 'configJson'");
            }
            inputs["configJson"] = args ? args.configJson : undefined;
            inputs["folder"] = args ? args.folder : undefined;
            inputs["slug"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Dashboard.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Dashboard resources.
 */
export interface DashboardState {
    /**
     * The JSON configuration for the dashboard.
     */
    readonly configJson?: pulumi.Input<string>;
    readonly folder?: pulumi.Input<number>;
    /**
     * A URL "slug" for this dashboard, generated by Grafana by removing
     * certain characters from the dashboard name given as part of the `configJson`
     * argument. This can be used to generate the URL for a dashboard.
     */
    readonly slug?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Dashboard resource.
 */
export interface DashboardArgs {
    /**
     * The JSON configuration for the dashboard.
     */
    readonly configJson: pulumi.Input<string>;
    readonly folder?: pulumi.Input<number>;
}
